#!/usr/bin/env python3

from sys import argv
from http.server import SimpleHTTPRequestHandler as Handler
from socketserver import TCPServer

PORT = 8000 if len(argv)==1 else int(argv[1])


with TCPServer(("",PORT), Handler) as httpd:
	print("serve at", PORT)
	httpd.serve_forever()


